### PR TITLE
feature/duplicated-containers-bug

### LINKED ISSUE #945: distage-framework-docker: Do not duplicate containers spawning in parallel when `reuse=true`
Currently even when `reuse` is turned on, containers may be duplicated under parallel tests when they launch at the same time, because their spawning is non-atomic.

Current plan: use `nio.FileLock` in temporary directory to signify that a reusable container is spawning and prevent duplicates from spawning

### PR DESCRIPTION
**Pull request by Caparow**
Fix #945

### CODE REVIEW

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala [hunk 1]
```diff
@@ -178,55 +183,89 @@ object DockerContainer {
...
-              availablePorts = Map.empty,
-              hostName = inspection.getConfig.getHostName
-            )
-            await(unverified)
+      }
+
+      val tmpDir = System.getProperty("java.io.tmpdir")
+      val filename = s"${config.image.replace("/", "_")}:${config.ports.mkString(";")}.tmp"
+      val file = new File(s"$tmpDir/$filename")
+      file.createNewFile()
```
Comment (neko-kai) [inline distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: Does something prevent using `File.createTempFile` here?

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala [hunk 2]
```diff
@@ -178,55 +183,89 @@ object DockerContainer {
...
+      file.deleteOnExit()
```
Comment (neko-kai) [inline distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: This will delay deletion by a lot in sbt, better add the file to `this.InnerResource` and cleanup inside `release` since we have this ability

**Review by neko-kai — COMMENTED** [review]
Wow, fantastic! ❤️

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala (hunk 2 above)
Comment (neko-kai) [reply distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: Actually, I guess we can just close it using bracket below, we don't need it after `eff` is finished right?

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala [hunk 3]
```diff
@@ -178,55 +183,89 @@ object DockerContainer {
...
+      DIEffect[F].bracketAuto(DIEffect[F].maybeSuspend(FileChannel.open(file.toPath, StandardOpenOption.WRITE))) {
+        acquireExclusiveLock(_) match {
+          case Some(v) => eff.guarantee(DIEffect[F].maybeSuspend(v.close()))
```
Comment (neko-kai) [inline distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: Doesn't this `v.close()` duplicate the closing in `bracketAuto`?..

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala (hunk 1 above)
Comment (neko-kai) [reply distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: Never mind, we need both the file and tmpdir to be non-random

File: distage/distage-framework-docker/src/test/scala/izumi/distage/testkit/docker/DistageTestDockerBIO2.scala [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+import izumi.distage.docker.examples.DynamoDocker
+import izumi.distage.testkit.TestConfig
+import izumi.distage.testkit.docker.fixtures.PgSvcExample
+import izumi.distage.testkit.scalatest.DistageBIOSpecScalatest
+import izumi.fundamentals.platform.properties.EnvVarsCI
+import izumi.logstage.api.Log
+import zio.IO
+
+// this tests needed to check mutex for reusable containers during parallel test runs
+final class DistageTestDockerBIO2 extends DistageBIOSpecScalatest[IO] {
```
Comment (neko-kai) [inline distage/distage-framework-docker/src/test/scala/izumi/distage/testkit/docker/DistageTestDockerBIO2.scala]: @Caparow Could you make top level classes with this test like 10-15 times with `moduleOverrides = new ModuleDef { make[UUID].fromValue(randomUUID()) }` to guarantee new test envs - to be able to check that the dockers do not duplicate by manual testing

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala (hunk 2 above)
Comment (Caparow) [reply distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: Yeah, good point, will do.

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala (hunk 1 above)
Comment (Caparow) [reply distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: @neko-kai tempFiles are created with random suffix, so they are cannot be used as the shared mutex.

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala [hunk 5]
```diff
@@ -178,55 +183,89 @@ object DockerContainer {
...
+      def acquireExclusiveLock(chanel: FileChannel, attempts: Int = 0): Option[FileLock] = {
+        logger.debug(s"Attempt ${attempts -> "num"} to acquire lock for ${config.image}.")
+        (try {
+          Option(chanel.tryLock())
+        } catch {
+          case _: OverlappingFileLockException => None
+        }) match {
+          case v@Some(_) => v
+          case None if attempts < maxAttempts =>
+            Thread.sleep(waitForMillis)
```
Comment (neko-kai) [inline distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: @Caparow I think with wait times above 50ms we should really use `DIEffectAsync.sleep` instead of threadDelay to avoid hogging up threads

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala (hunk 3 above)
Comment (Caparow) [reply distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: Yup, but we don't have FileLock during channel opening. So we need to release lock just after container upping.

File: distage/distage-framework-docker/src/test/scala/izumi/distage/testkit/docker/DistageTestDockerBIO2.scala (hunk 4 above)
Comment (Caparow) [reply distage/distage-framework-docker/src/test/scala/izumi/distage/testkit/docker/DistageTestDockerBIO2.scala]: done

File: distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala (hunk 5 above)
Comment (Caparow) [reply distage/distage-framework-docker/src/main/scala/izumi/distage/docker/DockerContainer.scala]: done

File: distage/distage-framework-docker/src/test/scala/izumi/distage/testkit/docker/DistageTestDockerBIO.scala [hunk 6]
```diff
@@ -30,10 +34,32 @@ final class DistageTestDockerBIO extends DistageBIOSpecScalatest[IO] {
...
-      ))
+      memoizationRoots = Set(DIKey.get[PgSvcExample]),
+      parallelTests = true,
+      parallelEnvs = true,
+      testRunnerLogLevel = Log.Level.Debug
+    )
   }
 }
+
+final class DistageTestDockerBIO1 extends DistageTestDockerBIO { override protected def config: TestConfig = DistageTestDockerBIO.randomEnv(super.config) }
```
Comment (neko-kai) [inline distage/distage-framework-docker/src/test/scala/izumi/distage/testkit/docker/DistageTestDockerBIO.scala]: @Caparow You can put this once into the super class, don't have to repeat always

Comment (Caparow) [reply distage/distage-framework-docker/src/test/scala/izumi/distage/testkit/docker/DistageTestDockerBIO.scala]: done

**Comment by neko-kai** [comment]
@Caparow Thank you so much! 🙏  This helps get a new release out A LOT
